# Generated by Django 3.2.4 on 2021-06-21 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(default=['USA'], max_length=155, verbose_name='Страна'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='release',
            field=models.DateField(default=datetime.date.today, verbose_name='Примьера в мире'),
        ),
        migrations.AlterField(
            model_name='movieshots',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='movie_shots/'),
        ),
    ]
